# Site settings
title: Melissa Suit
email: melsuit73@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: # twitter_username
github_username:  melsuit

# Build settings
markdown: CommonMarkGhPages

highlighter: rouge

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/


